# Generated by Django 3.2.7 on 2021-09-23 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nerds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nerd',
            old_name='name',
            new_name='nerdName',
        ),
    ]
