# Generated by Django 3.2.7 on 2021-09-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerds', '0002_rename_name_nerd_nerdname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nerd',
            name='nerdName',
            field=models.CharField(max_length=120),
        ),
    ]
