# Generated by Django 3.2.7 on 2021-09-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerds', '0003_alter_nerd_nerdname'),
    ]

    operations = [
        migrations.AddField(
            model_name='nerd',
            name='nerdFowards',
            field=models.IntegerField(default=0),
        ),
    ]
