# Generated by Django 3.2.7 on 2021-09-30 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nerds', '0007_alter_nerd_nerdsalt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nerd',
            name='nerdLogin',
        ),
        migrations.RemoveField(
            model_name='nerd',
            name='nerdPassword',
        ),
        migrations.RemoveField(
            model_name='nerd',
            name='nerdSalt',
        ),
    ]
