# Generated by Django 3.2.7 on 2021-09-30 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerds', '0008_auto_20210930_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='nerd',
            name='nerdLogin',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
