# Generated by Django 3.2.7 on 2021-09-30 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nerds', '0010_nerd_nerdemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nerd',
            name='nerdEmail',
        ),
    ]
