# Generated by Django 3.2.7 on 2021-09-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priorities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='priorityName',
            field=models.CharField(max_length=30),
        ),
    ]
