# Generated by Django 3.2.7 on 2021-09-23 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='category',
            new_name='categoryCall',
        ),
        migrations.RenameField(
            model_name='call',
            old_name='client',
            new_name='clientCall',
        ),
        migrations.RenameField(
            model_name='call',
            old_name='description',
            new_name='descriptionCall',
        ),
        migrations.RenameField(
            model_name='call',
            old_name='subject',
            new_name='subjectCall',
        ),
    ]
