# Generated by Django 3.2.7 on 2021-09-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_auto_20210923_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='companyCall',
            field=models.TextField(default='CompanyName', max_length=30),
        ),
        migrations.AddField(
            model_name='call',
            name='emailResponseCall',
            field=models.EmailField(default='emailofcompany@domainname.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='call',
            name='categoryCall',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='call',
            name='clientCall',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='call',
            name='subjectCall',
            field=models.CharField(max_length=60),
        ),
    ]
