# Generated by Django 3.2.7 on 2021-09-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_auto_20210923_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='call',
            name='companyCall',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='call',
            name='emailResponseCall',
            field=models.EmailField(max_length=254),
        ),
    ]
