# Generated by Django 3.2.7 on 2021-09-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_auto_20210923_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='solution',
            field=models.TextField(default=''),
        ),
    ]
