# Generated by Django 3.2.7 on 2021-09-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0006_auto_20210925_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='priorityCall',
            field=models.IntegerField(default=0),
        ),
    ]
