# Generated by Django 3.2.7 on 2021-09-27 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0007_call_prioritycall'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='dateTimeCall',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
