# Generated by Django 3.2.7 on 2021-09-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0008_call_datetimecall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='nerdCall',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
